Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://github.com/pscedu/singularity-aspera-connect
    COPYRIGHT Copyright © 2021-2023 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 4.2.8

%files
    ibm-aspera-connect_4.2.8.540_linux_x86_64.sh /opt

%post
    ls -lta /opt
    chmod +x /opt/ibm-aspera-connect_4.2.8.540_linux_x86_64.sh
    bash /opt/ibm-aspera-connect_4.2.8.540_linux_x86_64.sh
    cp -rv ~/.aspera /opt/aspera
    ln -s /opt/aspera/connect/bin/ascp /usr/bin/ascp
    ln -s /opt/aspera/connect/bin/asperaconnect /usr/bin/asperaconnect
    ln -s /opt/aspera/connect/bin/asperacrypt /usr/bin/asperacrypt

%runscript
    /usr/bin/ascp "$@"
